name: pe_lingam
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.2.25=h06a4308_0
  - expat=2.7.1=h6a678d5_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.16=h5eee18b_0
  - pip=25.1=pyhc872135_2
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.11.13=h1a3bd86_0
  - readline=8.2=h5eee18b_0
  - setuptools=78.1.1=py311h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h993c535_1
  - wheel=0.45.1=py311h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - asttokens==3.0.0
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - comm==0.2.2
      - contourpy==1.3.2
      - cycler==0.12.1
      - debugpy==1.8.14
      - decorator==5.2.1
      - einops==0.8.1
      - executing==2.2.0
      - filelock==3.18.0
      - fonttools==4.58.4
      - fsspec==2025.5.1
      - graphviz==0.21
      - hf-xet==1.1.10
      - huggingface-hub==0.35.3
      - hyper-connections==0.2.1
      - idna==3.10
      - igraph==0.11.9
      - ipykernel==6.29.5
      - ipython==9.3.0
      - ipython-pygments-lexers==1.1.1
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.5.1
      - jsonpickle==4.1.1
      - jupyter-client==8.6.3
      - jupyter-core==5.8.1
      - kiwisolver==1.4.8
      - lingam==1.10.0
      - markupsafe==3.0.2
      - matplotlib==3.10.3
      - matplotlib-inline==0.1.7
      - mpmath==1.3.0
      - nest-asyncio==1.6.0
      - networks==0.3.7
      - networkx==3.5
      - numdifftools==0.9.41
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - packaging==25.0
      - pandas==2.3.0
      - parso==0.8.4
      - patsy==1.0.1
      - pexpect==4.9.0
      - pillow==11.2.1
      - platformdirs==4.3.8
      - progressbar2==4.5.0
      - prompt-toolkit==3.0.51
      - psutil==7.0.0
      - psy==0.0.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pygam==0.9.1
      - pygments==2.19.2
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - python-utils==3.9.1
      - pytz==2025.2
      - pyyaml==6.0.2
      - pyzmq==27.0.0
      - regex==2025.9.18
      - requests==2.32.5
      - safetensors==0.6.2
      - scikit-learn==1.7.0
      - scipy==1.11.4
      - seaborn==0.13.2
      - semopy==2.3.11
      - six==1.17.0
      - stack-data==0.6.3
      - statsmodels==0.14.4
      - sympy==1.14.0
      - texttable==1.7.0
      - threadpoolctl==3.6.0
      - tokenizers==0.22.1
      - torch==2.7.1
      - tornado==6.5.1
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.57.0
      - triton==3.3.1
      - typing-extensions==4.14.0
      - tzdata==2025.2
      - urllib3==2.5.0
      - wcwidth==0.2.13
prefix: /home/yunze/anaconda3/envs/pe_lingam
